version: '3.2'

services:
  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elasticsearch/data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: krwcitygI6j83LiL0fYZ
      TZ: Asia/Shanghai
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - devops

  logstash:
    image: logstash:$ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
      - type: bind
        source: /Users/Jormin/GeoIP
        target: /usr/share/GeoIP
        read_only: true
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:$ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    depends_on:
      - elasticsearch

  filebeat:
    image: filebeat:$ELK_VERSION
    restart: "no"
    command: "filebeat -e -d *"
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: /Users/Jormin/logs
        target: /var/log
      - type: bind
        source: /Users/Jormin/code/vchangyi/gw-shop-v1/src/storage/logs
        target: /var/log/gw-shop-v1
      - type: bind
        source: /Users/Jormin/code/vchangyi/callback/src/storage/test-logs
        target: /var/log/callback
      - type: bind
        source: /Users/Jormin/docker/docker-dev-php/nginx/logs
        target: /var/log/nginx
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    links:
      - "logstash:logstash"
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    networks:
      - devops

networks:
  devops:
    external: true
