setup.kibana:
  host: "kibana:5601"

filebeat:
  inputs:
    - input_type: log
      paths:
        - /var/log/*.log
    - input_type: stdin
      paths:
        - /var/log/*.log

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info