setup.kibana:
  host: "kibana:5601"

filebeat:
  inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/fetcher/*/*.log
      fields: 
        source: fetcher
    - type: log
      enabled: true
      paths:
        - /var/log/licaidaily/*/*.log
      fields: 
        source: licaidaily
    - type: log
      enabled: true
      paths:
        - /var/log/go-tools/*/*.log
      fields: 
        source: go-tools

processors:
  - decode_json_fields:
      fields: [message] # 要进行解析的字段
      target: "" # json内容解析到指定的字段，如果为空（“”），则解析到顶级结构下
      process_array: false # 如果解析出的json结构中某个字段在原始的event（在filebeat中传输的一条数据为一个event）中也存在，是否覆盖event中该字段的值，默认值:false
      process_array: false # 数组是否解码，默认值:false
      max_depth: 1 # 解码深度，默认值：1
      
output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
